"""
Adjustment Engine
=================
Roll, surrender, re-leg, or convert multi-leg option positions
based on configurable rules.

Processes AdjustmentRequest objects generated by the LegMonitor and
executes the mechanical actions (close legs, open new legs, update positions).

Supported adjustments:
  ROLL_UP    — move short strike higher (bearish shift)
  ROLL_DOWN  — move short strike lower (bullish shift)
  ROLL_OUT   — close current leg, re-open at next expiry (same strike)
  WIDEN_WINGS — move protection legs further OTM
  NARROW_WINGS — tighten wing width
  ADD_LEG    — add a new leg to an existing structure
  REMOVE_LEG — close a specific leg
  CONVERT    — transform structure (e.g. iron condor → iron butterfly)
  SURRENDER  — close all legs at market
"""
from __future__ import annotations

import logging
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from src.models.options import (
    AdjustmentRequest,
    AdjustmentType,
    LegSignal,
    LegPosition,
    LegAction,
    MultiLegPosition,
    OptionType,
    PositionStatus,
    StructureType,
)
from src.services.multi_leg_executor import multi_leg_executor
from src.services.options_position_manager import options_position_manager
from src.services.option_chain import option_chain_service, STRIKE_STEPS, DEFAULT_STRIKE_STEP

logger = logging.getLogger(__name__)


class AdjustmentEngine:
    """
    Processes adjustment requests and modifies live positions.
    Each adjustment type has a dedicated handler.
    """

    # Router
    _HANDLERS = {
        AdjustmentType.SURRENDER: "_handle_surrender",
        AdjustmentType.ROLL_UP: "_handle_roll",
        AdjustmentType.ROLL_DOWN: "_handle_roll",
        AdjustmentType.ROLL_OUT: "_handle_roll_out",
        AdjustmentType.WIDEN_WINGS: "_handle_widen_wings",
        AdjustmentType.NARROW_WINGS: "_handle_narrow_wings",
        AdjustmentType.ADD_LEG: "_handle_add_leg",
        AdjustmentType.REMOVE_LEG: "_handle_remove_leg",
        AdjustmentType.CONVERT: "_handle_convert",
    }

    async def process(self, request: AdjustmentRequest) -> bool:
        """
        Execute an adjustment request.
        Returns True if successful, False otherwise.
        """
        handler_name = self._HANDLERS.get(request.adjustment_type)
        if not handler_name:
            logger.error(f"No handler for adjustment type: {request.adjustment_type}")
            return False

        pos = options_position_manager.get_position(request.position_id)
        if not pos:
            logger.error(f"Position not found: {request.position_id}")
            return False

        logger.info(
            f"Adjustment: {request.adjustment_type.value} on {request.position_id} "
            f"| reason: {request.reason}"
        )

        pos.status = PositionStatus.ADJUSTING
        handler = getattr(self, handler_name)
        try:
            success = await handler(pos, request)
            if success:
                pos.adjustments.append({
                    "type": request.adjustment_type.value,
                    "reason": request.reason,
                    "timestamp": datetime.now().isoformat(),
                    "metadata": request.metadata,
                })
                if pos.status == PositionStatus.ADJUSTING:
                    # If handler didn't change status, set back to OPEN
                    pos.status = PositionStatus.OPEN if pos.open_legs else PositionStatus.CLOSED
            else:
                pos.status = PositionStatus.OPEN  # revert
            return success
        except Exception as e:
            logger.error(f"Adjustment failed: {e}", exc_info=True)
            pos.status = PositionStatus.OPEN
            return False

    async def process_batch(self, requests: List[AdjustmentRequest]) -> int:
        """Process multiple adjustment requests. Returns count of successful."""
        success_count = 0
        for req in requests:
            if await self.process(req):
                success_count += 1
        return success_count

    # ------------------------------------------------------------------
    # Handlers
    # ------------------------------------------------------------------
    async def _handle_surrender(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """Close all open legs at market."""
        legs_to_close = pos.open_legs
        if req.legs_to_close:
            legs_to_close = [l for l in pos.legs if l.leg_id in req.legs_to_close and l.status == "OPEN"]

        if not legs_to_close:
            pos.status = PositionStatus.CLOSED
            pos.closed_at = datetime.now()
            return True

        exit_orders = await multi_leg_executor.close_legs(legs_to_close)

        # Calculate realized P&L
        realized = sum(
            leg.unrealized_pnl for leg in legs_to_close
        )
        pos.realized_pnl += realized

        if not pos.open_legs:
            pos.status = PositionStatus.CLOSED
            pos.closed_at = datetime.now()
            options_position_manager.close_position(pos.position_id, pos.realized_pnl)

        logger.info(f"Surrender completed: {len(exit_orders)} legs closed, pnl={realized:+.2f}")
        return True

    async def _handle_roll(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """
        Roll a leg up or down (change strike, same expiry).
        Closes the breached leg and opens a new one at a shifted strike.
        """
        direction = 1 if req.adjustment_type == AdjustmentType.ROLL_UP else -1
        step = STRIKE_STEPS.get(pos.symbol.upper(), DEFAULT_STRIKE_STEP)

        # Identify legs to roll
        legs_to_roll = pos.open_legs
        if req.legs_to_close:
            legs_to_roll = [l for l in pos.legs if l.leg_id in req.legs_to_close and l.status == "OPEN"]

        if not legs_to_roll:
            return False

        for old_leg in legs_to_roll:
            # Close old leg
            exit_orders = await multi_leg_executor.close_legs([old_leg])

            # Open new leg at shifted strike
            new_strike = old_leg.strike + direction * step
            new_leg_signal = LegSignal(
                symbol=old_leg.symbol,
                option_type=old_leg.option_type,
                strike=new_strike,
                expiry=old_leg.expiry,
                action=old_leg.action,
                quantity=old_leg.quantity,
                lot_size=old_leg.lot_size,
            )
            new_legs = await multi_leg_executor.execute_legs([new_leg_signal], pos.symbol)
            if new_legs:
                pos.legs.extend(new_legs)
                logger.info(
                    f"Rolled {old_leg.option_type.value} {old_leg.strike} → {new_strike}"
                )

        return True

    async def _handle_roll_out(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """Roll to next expiry (same strike)."""
        legs_to_roll = pos.open_legs
        if req.legs_to_close:
            legs_to_roll = [l for l in pos.legs if l.leg_id in req.legs_to_close and l.status == "OPEN"]

        if not legs_to_roll:
            return False

        # Fetch next expiry from option chain
        chain = await option_chain_service.get_chain(pos.symbol, num_strikes=1)
        if not chain.expiry_dates or len(chain.expiry_dates) < 2:
            logger.warning("Cannot roll out — no next expiry available")
            return False

        next_expiry = chain.expiry_dates[1]  # second expiry

        for old_leg in legs_to_roll:
            await multi_leg_executor.close_legs([old_leg])

            new_leg_signal = LegSignal(
                symbol=old_leg.symbol,
                option_type=old_leg.option_type,
                strike=old_leg.strike,
                expiry=next_expiry,
                action=old_leg.action,
                quantity=old_leg.quantity,
                lot_size=old_leg.lot_size,
            )
            new_legs = await multi_leg_executor.execute_legs([new_leg_signal], pos.symbol)
            if new_legs:
                pos.legs.extend(new_legs)
                logger.info(
                    f"Rolled out {old_leg.option_type.value} {old_leg.strike} "
                    f"from {old_leg.expiry} → {next_expiry}"
                )

        return True

    async def _handle_widen_wings(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """
        Move protection (buy) legs further OTM to reduce margin / widen spread.
        Applies to iron condors, spreads, etc.
        """
        step = STRIKE_STEPS.get(pos.symbol.upper(), DEFAULT_STRIKE_STEP)
        buy_legs = [l for l in pos.open_legs if l.action == LegAction.BUY]

        if not buy_legs:
            return False

        for old_leg in buy_legs:
            # Widen: move CE buys higher, PE buys lower
            direction = 1 if old_leg.option_type == OptionType.CE else -1
            new_strike = old_leg.strike + direction * step

            await multi_leg_executor.close_legs([old_leg])
            new_leg_signal = LegSignal(
                symbol=old_leg.symbol,
                option_type=old_leg.option_type,
                strike=new_strike,
                expiry=old_leg.expiry,
                action=old_leg.action,
                quantity=old_leg.quantity,
                lot_size=old_leg.lot_size,
            )
            new_legs = await multi_leg_executor.execute_legs([new_leg_signal], pos.symbol)
            if new_legs:
                pos.legs.extend(new_legs)

        return True

    async def _handle_narrow_wings(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """Move protection legs closer to short strikes."""
        step = STRIKE_STEPS.get(pos.symbol.upper(), DEFAULT_STRIKE_STEP)
        buy_legs = [l for l in pos.open_legs if l.action == LegAction.BUY]

        if not buy_legs:
            return False

        for old_leg in buy_legs:
            direction = -1 if old_leg.option_type == OptionType.CE else 1
            new_strike = old_leg.strike + direction * step

            await multi_leg_executor.close_legs([old_leg])
            new_leg_signal = LegSignal(
                symbol=old_leg.symbol,
                option_type=old_leg.option_type,
                strike=new_strike,
                expiry=old_leg.expiry,
                action=old_leg.action,
                quantity=old_leg.quantity,
                lot_size=old_leg.lot_size,
            )
            new_legs = await multi_leg_executor.execute_legs([new_leg_signal], pos.symbol)
            if new_legs:
                pos.legs.extend(new_legs)

        return True

    async def _handle_add_leg(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """Add new legs specified in the request."""
        if not req.new_legs:
            logger.warning("ADD_LEG request with no new_legs specified")
            return False

        new_positions = await multi_leg_executor.execute_legs(req.new_legs, pos.symbol)
        pos.legs.extend(new_positions)
        return bool(new_positions)

    async def _handle_remove_leg(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """Close specific legs without replacement."""
        legs_to_remove = [l for l in pos.legs if l.leg_id in req.legs_to_close and l.status == "OPEN"]
        if not legs_to_remove:
            return False
        await multi_leg_executor.close_legs(legs_to_remove)
        return True

    async def _handle_convert(
        self, pos: MultiLegPosition, req: AdjustmentRequest
    ) -> bool:
        """
        Convert one structure to another.
        E.g., iron condor → iron butterfly (move short strikes to ATM).
        """
        target_structure = req.metadata.get("target_structure")
        if not target_structure:
            logger.warning("CONVERT request with no target_structure in metadata")
            return False

        # Close all existing legs
        await multi_leg_executor.close_legs(pos.open_legs)

        # Execute new legs
        if req.new_legs:
            new_positions = await multi_leg_executor.execute_legs(req.new_legs, pos.symbol)
            pos.legs.extend(new_positions)

        try:
            pos.structure_type = StructureType(target_structure)
        except ValueError:
            pass

        return True


# Module-level singleton
adjustment_engine = AdjustmentEngine()
